export const categories = [
  {
    id: 1,
    lable: "Cua biển Cà Mau",
    image: "/images/cua-bien.jpg",
    description: "Tỉnh Cà Mau có chiều dài bờ biển 254 km, gần 70.000 ha đất rừng ngập mặn và trên 250.000 ha đất nuôi tôm kết hợp với các loài thủy sản khác nên sản lượng cua ở Cà Mau luôn dẫn đầu trong cả nước. Cua là một trong những mặt hàng có giá trị kinh tế cao và được đông đảo người tiêu dùng ưa chuộng. ",
  },
  {
    id: 2,
    lable: "Cá thòi lòi",
    image: "/images/ca-thoi-loi.jpg",
    description: "Nó sinh sống được ở vùng nước mặn, nước lợ. Nó có hai chân trước, bơi lội dưới sông, di chuyển trên bùn, chạy nhảy trên cạn và kỳ lạ hơn là nó có thể leo trèo trên cây.",
  },
  {
    id: 3,
    lable: "Tôm sú Cà Mau",
    image: "/images/tom-su.jpeg",
    description: "Nhờ được nuôi trên vùng đất ngập mặn ven biển, được phù sa bồi đắp, nguồn nước không bị ô nhiễm, con tôm sú Cà Mau lớn con, là loại thực phẩm đặc sản, ngon, bổ dưỡng, tốt cho sức khỏe con người, có giá trị kinh tế cao và được thị trường ở nhiều nước trên thế giới ưa chuộng. Năm 2016, tỉnh Cà Mau ước đạt tổng sản lượng tôm nuôi 156.000 tấn. Trong đó, con tôm sú đóng vai trò chủ yếu",
  },
  {
    id: 4,
    lable: "Lươn",
    image: "/images/luon.jpeg",
    description: "Từ thời đi khẩn hoang mở cõi, phần lớn đồng đất của Cà Mau là vùng “cầm thủy”, quanh năm đọng nước. Do ảnh hưởng của điều kiện tự nhiên nên đồng đất Cà Mau rất thích hợp để các loài cá đồng sinh sôi, nẩy nở. Ngoài các loại cá đồng như cá lóc, cá trê, cá rô, cá bổi, cá thác lác, rùa, rắn… thì lươn cũng được xem là một trong những loại đặc sản có giá trị kinh tế cao của đồng đất Cà Mau.",
  },
  {
    id: 5,
    lable: "Nghêu Khai Long",
    image: "/images/ngeu-khai-long.png",
    description: "Ngoài tôm, cá, cua, hàu, vọp, ốc len, sò huyết… vùng Đất Mũi, huyện Ngọc Hiển, tỉnh Cà Mau còn có một loại đặc sản rất nổi tiếng và có giá trị kinh tế cao đó là nghêu Khai Long.",
  },
  {
    id: 6,
    lable: "Hàu Đất Mũi",
    image: "/images/hau.jpg",
    description: "Do nằm sát biển và có hệ thống sông ngòi, kênh rạch chằng chịt nên vùng đất ven sông, ven biển của vùng Đất Mũi Cà Mau rất thích hợp cho hàu sinh sôi, trú ngụ.",
  },
  {
    id: 7,
    lable: "Cá rô đồng U Minh",
    image: "/images/ca-ro-dong-u-minh.jpg",
    description: "Rừng tràm U Minh được bao bọc bởi hệ thống các con sông Ông Đốc, Cái Tàu, Trèm Trẹm và gờ đất cao ven biển Tây tạo thành vùng trũng treo quanh năm đọng nước. Vùng đất “cầm thủy” U Minh với cánh rừng tràm bạt ngàn chính là chiếc nôi cho các loài cá đồng trú ngụ, sinh sôi nẩy nở.",
  },
  {
    id: 8,
    lable: "Cá kèo",
    image: "/images/ca-keo.jpg",
    description: "Ngày xưa ở Cà Mau cá kèo nhiều vô số kể. Một hàng đáy trên sông nếu đúng vào con nước, có thể thu hoạch hàng tấn cá kèo mỗi đêm. Ngày nay, cá kèo trong môi trường tự nhiên không còn nhiều như ngày xưa nên người ta đã bắt đầu nuôi để cung cấp cho nhu cầu của thị trường.",
  },
  {
    id: 9,
    lable: "Cá ngát",
    image: "/images/ca-ngat.jpg",
    description: "Cá ngát là một trong những đặc sản nổi tiếng và có giá trị kinh tế cao của vùng Đất Mũi Cà Mau. Loại sản vật này được chế biến thành nhiều món ăn ngon trong thực đơn ở các nhà hàng từ bình dân đến sang trọng.",
  },
  {
    id: 10,
    lable: "Cá nâu",
    image: "/images/Ca-Nau.jpg",
    description: "Cá nâu có thân hình dẹp, mình có nhiều đốm đen. Cá nâu sống ở môi trường nước mặn, nước lợ và sinh sống nhiều trên các tuyến kênh rạch của vùng rừng ngập mặn, các cửa sông, các đảo ven biển và các ao đầm nuôi tôm. Cùng với con tôm, con cua, cá nâu là một trong những đặc sản có giá trị kinh tế cao của vùng đất ngập mặn ven biển ở Cà Mau.",
  },
  {
    id: 11,
    lable: "Cá bớp",
    image: "/images/ca-bop.jpg",
    description: "Tỉnh Cà Mau có chiều dài bờ biển trên 254km, với 3 mặt giáp biển và có ngư trường rộng lớn. Trên biển có đảo Hòn Khoai, Hòn Chuối, Hòn Buông và Hòn Đá Bạc. Vùng biển Tây Nam tỉnh Cà Mau nằm trong vùng biển Vịnh Thái Lan, quanh năm kín gió, nguồn nước sạch, không bị ô nhiễm nên có trữ lượng lớn cá bớp sinh sống, trú ngụ.",
  },
  {
    id: 12,
    lable: "Cá chẽm",
    image: "/images/ca-chem.jpg",
    description: "Cùng với nhiều loại thủy, hải sản khác, cá chẽm là một trong những đặc sản có giá trị kinh tế cao của vùng Đất Mũi Cà Mau",
  },
  {
    id: 13,
    lable: "Khô cá khoai Cái Đôi Vàm",
    image: "/images/kho-ca-khoai.jpg",
    description: "Khô cá khoai từ lâu đã trở thành đặc sản nổi tiếng của làng biển thị trấn Cái Đôi Vàm, huyện Phú Tân, tỉnh Cà Mau. Hàng năm, làng nghề truyền thống nơi đây cung cấp cho thị trường hàng nghìn tấn cá khô khoai đặc sản và được người tiêu dùng gần xa ưa chuộng, chọn mua, nhất là để tiêu dùng, làm quà biếu cho bạn bè, người thân trong dịp Xuân về, Tết đến.",
  },
  {
    id: 14,
    lable: "Tôm càng xanh",
    image: "/images/tom-cang-xanh.webp",
    description: "Từ lâu, đồng đất, kênh rạch vùng ngọt hóa tỉnh Cà Mau đã trở thành chiếc nôi cho loài tôm càng xanh sinh sôi, phát triển. Trong đó, các huyện Thới Bình, U Minh, Trần Văn Thời được mệnh danh là “vương quốc” tôm càng xanh ở Cà Mau. Không chỉ là địa phương dẫn đầu cả tỉnh về diện tích, năng suất, sản lượng mà nhiều hộ nông dân nơi đây còn biết áp dụng khoa học kỹ thuật để nuôi tôm càng xanh",
  },
  {
    id: 15,
    lable: "Cá dứa Cà Mau",
    image: "/images/ca-dua.jpg",
    description: "Cá dứa là một đặc sản ở Cà Mau. Cá dứa có giá trị kinh tế cao và có thể chế biến được nhiều món ăn ngon và bổ dưỡng. Sở dĩ, loài cá này có tên gọi là cá dứa là do khi ăn thịt cá toát lên thoang thoảng mùi thơm của lá dứa (loại lá dùng để làm bánh phổ biến ở miền Tây).",
  },
  {
    id: 16,
    lable: "Tôm lụi",
    image: "/images/tom-lui.jpg",
    description: "Tôm lụi thực ra là tôm tươi, được lột vỏ, xỏ lụi, phơi khô. Đây là một trong những đặc sản có từ lâu đời của vùng Đất Mũi Cà Mau.\nNhững năm sau ngày giải phóng miền Nam, tôm tự nhiên trong sông rạch còn nhiều nên việc khai thác, đánh bắt tôm của người dân ở Cà Mau đạt năng suất, sản lượng rất cao. Nhiều hộ nông dân, mỗi nước xổ tôm thu hoạch đến vài tấn. Sản phẩm thu được chủ yếu là tôm đất, tôm bạc và tôm xà búi (tôm thẻ đuôi đỏ). Tôm thu hoạch được ít người mua, phần lớn chỉ để ăn hoặc luộc để làm tôm khô nhưng giá thành lại không cao. Do đó, sau khi đánh bắt được tôm, ngoài làm thực phẩm tươi sống, làm tôm khô, chả tôm, bánh phồng tôm, mắm tôm, mắm ruốc (thực ra nguyên liệu làm từ tôm nhưng tôm được băm nhuyễn trộn với gia vị như muối, đường, ớt, tỏi, gừng, rượu trắng...phơi nắng khoảng 3, 4 ngày là có thể ăn được), người dân Cà Mau còn nghĩ ra cách làm tôm lụi để ăn dần.",
  },
  {
    id: 17,
    lable: "Khô cá đù",
    image: "/images/kho-ca-du.jpg",
    description: "Làng biển thị trấn Cái Đôi Vàm, huyện Phú Tân, tỉnh Cà Mau, từ lâu rất nổi tiếng với nghề làm cá khô truyền thống. Ngoài các mặt hàng cá khô nổi tiếng như cá khô khoai, cá mai, tôm tích, cá rún, ngư dân Cái Đôi Vàm còn sản xuất khô cá đù rất đặc trưng của làng biển xứ này.",
  },
  {
    id: 18,
    lable: "Khô cá đuối",
    image: "/images/kho-ca-duoi.jpg",
    description: "Cá đuối sinh sống nhiều trên vùng biển Cà Mau. Cá đuối tươi có thể chế biến được nhiều món ăn ngon như hấp hành, nấu lẩu, chiên, nướng hoặc nấu sả nghệ. Tuy nhiên, cá đuối làm khô nướng trên bếp than hồng chấm với nước mắm me hoặc nước giấm ớt thì mới đúng là món ăn khoái khẩu của nhiều người.\nCá đuối là một loài cá biển, mình và đầu có nhiều sụn, thân hình dẹp và xòe ra như chiếc quạt. Cá đuối có đuôi cá dài. thường sinh sống và ẩn nấp dưới đáy biển. Cá đuối có nhiều loại như đuối ó, đuối én, đuối bông, đuối sen, đuối đen… Những con lớn có trọng lượng lên đến vài chục kg.\nLàm khô cá đuối không cầu kỳ và cũng không khó. Tuy nhiên, để làm được khô cá đuối thơm ngon thì đòi hỏi phải có tay nghề và kinh nghiệm.\nThông thường, cá đuối tươi làm sạch, cắt thành từng miếng cỡ bằng bàn tay rồi tẩm gia vị đem phơi khô. Muốn cầu kỳ và đẹp mắt hơn, có thể cắt cá thành từng miếng hình cánh quạt, sau đó xẻ dọc từng khứa, mỗi khứa bằng ngón tay, khứa làm sao từng miếng cá không rời ra mà còn dính lại, nhìn như những chiếc quạt nan. Khứa cá xong, đem ướp gia vị như nước mắm, nước muối, đường, ớt, sả khoảng 20 phút cho thấm gia vị rồi đem phơi nắng. Tuy nhiên, không nên ướp cá quá mặn hoặc quá lạt. Nếu ướp quá mặn thì mùi vị sẽ mất ngon, còn quá lạt thì thịt sẽ bủn.  Làm khô cá đuối phải phơi cho đặng nắng, nếu phơi không đặng nắng thịt cá khô không được săn chắc và có mùi hơi hăn hắc.\nKhô cá đuối ở Cà Mau được sản xuất nhiều ở các làng cá ven biển như Sông Đốc, Khánh Hội, Cái Đôi Vàm, Hố Gùi, Gành Hào, Rạch Gốc… Đặc sản khô đuối Cà Mau thường sản xuất từ nguồn cá nguyên liệu tươi, không có sử dụng phẩm màu, chất bảo quản nên đảm bảo an toàn vệ sinh thực phẩm.\nKhô cá đuối có thể chế biến được nhiều món ăn ngon. Tuy nhiên, ngon nhất và hấp dẫn nhất là khô cá đuối nướng trên bếp than hồng chấm với nước mắm me.\nTừ lâu, khô cá đuối là đặc sản của xứ biển Cà Mau. Hiện nay, giá khô cá đuối dao động khoảng 300.000 đồng/kg và rất thích hợp để làm quà tặng cho bạn bè, người thân mỗi khi Xuân về, Tết đến.",
  },
  {
    id: 19,
    lable: "Cá Khoai",
    image: "/images/Ca-khoai.jpg",
    description: "Cá Khoai là sản phẩm đặc sản đặc trưng của thị trấn Cái Đôi Vàm, huyện Phú Tân vừa được Cục Sở hữu trí tuệ - Bộ Khoa học và Công nghệ công nhận nhãn hiệu tập thể.\nThị trấn Cái Đôi Vàm là vùng ven biển của huyện Phú Tân, thế mạnh là nuôi trồng và khai thác thủy sản. Trong đó, Cá Khoai là một sản phẩm đặc sản nổi tiếng từ lâu được khách hàng nhiều nơi trong cả nước ưa chuộng. Trên địa bàn thị trấn Cái Đôi Vàm hiện nay có hơn 100 doanh nghiệp và hộ gia đình sản xuất, kinh doanh nghề Cá Khoai. Người dân thị trấn Cái Đôi Vàm cho biết: nghề khai thác Cá Khoai ở đây có từ rất lâu, cái nghề cha truyền, con nối, nhưng không xác định được mốc thời gian cụ thể.\nCá Khoai được chế biến nhiều món ăn hấp dẫn như: nấu lẩu, nấu cháo, chiên bột, làm khô… Cá khô khoai thì nhiều nơi làm, nhưng cá khô khoai thị trấn Cái Đôi Vàm đặc biệt hơn nơi khác và ngon hơn so với nhiều nơi khác. Vấn đề ở đây là cách chế biến. Nó phụ thuộc vào nhiều yếu tố, như: cách muối ướp đá, cách phơi thế nào, thời gian phơi bao lâu. Kinh nghiệm của người làm khô đóng vai trò quan trọng. Kinh nghiệm làm khô ở đây chính là giữ sao cho cá còn nguyên chất, sạch sẽ để phơi và phơi trên giàn, đón nắng đầy đủ. Thực hiện quy trình bảo quản hợp lý để đảm bảo chất lượng.\nHằng năm, cứ vào khoảng tháng 10 đến tháng 4 âm lịch; vào mỗi con nước, miền biển Cái Đôi Vàm, huyện Phú Tân lại sôi động và nhộn nhịp hẳn lên với nghề chế biến khô khoai. Người rửa, người ướp cá, người vắt cá lên giàn, người thu gom, phân loại, bó lại đóng gói… Để kịp đón nắng, phải bắt đầu công việc vắt cá từ khoảng 1 giờ khuya. Công việc này ai cũng có thể làm được, kể cả nam, nữ, người già, thanh niên và cả trẻ em.\nCá khoai Cái Đôi Vàm được Cục Sở hữu trí tuệ - Bộ Khoa học và Công nghệ cấp chứng nhận bảo hộ sản phẩm tập thể. Đây là điều kiện thuận lợi để người dân liên kết với nhau trong phát triển sản xuất, nâng cao hơn nữa chất lượng sản phẩm, đảm bảo giá cả và cạnh tranh trên thị trường. Đồng thời, hướng tới sản xuất sản phẩm đạt tiêu chuẩn xuất khẩu ra thị trường thế giới.",
  },
  {
    id: 20,
    lable: "Cua Năm Căn",
    image: "/images/cua-nam-can.jpg",
    description: "Cua Năm Căn - Cà Mau cùng với các đặc sản: mật ong U Minh, tôm khô Rạch Gốc, khô bổi U Minh, mắm cá lóc Thới Bình, cá chình cá bống tượng Tân Thành, bồn bồn Cái Nước đã được Cục Sở hữu trí tuệ Bộ Khoa học và Công nghệ công nhận nhãn hiệu tập thể.\nNăm Căn là một huyện ven biển thuộc tỉnh Cà Mau, có vị trí địa lý khá đặc biệt - với 2 mặt giáp biển - và có hệ thống sông ngòi, kênh rạch chằng chịt. Phần lớn diện tích đất sản xuất của huyện Năm Căn là đất rừng hoặc tiếp giáp với rừng ngập mặn Cà Mau, là vùng đầm lầy quanh năm ngập nước. Trên địa bàn còn có dòng sông Cửa Lớn. Đây là dòng sông không có hạ nguồn và cũng không có thượng nguồn, được chảy từ biển Đông ra biển Tây. Dòng sông Cửa Lớn quanh năm chở phù sa về bồi đắp cho vùng đất ngập mặn ven biển của huyện Năm Căn và các vùng đất lân cận. Do được phù sa bồi đắp, độ mặn ổn định và có nguồn thức ăn dồi dào nên phần lớn diện tích đất sản xuất (chủ yếu là đất nuôi trồng thủy sản) trên địa bàn huyện Năm Căn rất thích hợp loài của biển từ các cửa sông, biển tìm về đây sinh sống, trú ngụ.\nCua Năm Căn – Cà Mau phần lớn sinh trưởng trong môi trường tự nhiên, chủ yếu ăn thịt cá (không phải thức ăn công nghiệp) nên lớn con, chắc thịt, thịt cua ngon ngọt, gạch cua thì béo ngậy và rất giàu dinh dưỡng. Đặc biệt, Cua Năm Căn – Cà Mau có sức sống tốt hơn cua các vùng khác nên có thể vận chuyển được xa hơn, vài ngày hơn so với cua các vùng miền khác. Cua Năm Căn - Cà Mau không chỉ được người tiêu dùng trong tỉnh ưa chuộng mà còn được tiêu thụ mạnh tại các thị trường lớn trong nước như Hà Nội, Đà Nẵng, TP.Hồ Chí Minh, Cần Thơ. Đồng thời, còn mở rộng xuất khẩu sang các nước Trung Quốc, Hàn Quốc.\nNhằm giữ vững thương hiệu và đảm bảo quyền lợi cho người tiêu dùng, Ban quản lý nhãn hiệu Cua Năm Căn - Cà Mau đã tăng cường giám sát, kiểm tra chất lượng sản phẩm khi gắn nhãn, cũng như việc quản lý sử dụng nhãn hiệu tập thể. Theo đó, tại các cơ sở sản xuất kinh doanh cua trên địa bàn huyện chỉ chọn xuất bán và dán nhãn 2 loại cua y chắc và cua gạch, tuyệt đối không chọn cua ốp để bán nhằm bảo vệ nguồn lợi và để không làm mất uy tín nhãn hiệu. Mặt khác, cua được gắn nhãn hiệu “Cua Năm Căn - Cà Mau” chỉ có 2 loại: 1 và 2 và có quy định kích cỡ cho từng loại. Cua y từ 2 con/kg trở lên hay 2-3 con cua gạch/kg là loại 1; cua y từ 3-4 con/kg hay 3-5 con cua gạch/kg và loại 1 bị gảy 1 càng, ngoe là loại 2 và không chọn đóng bao, gắn nhãn loại trên 5 con/kg bất kể cua y hay cua gạch để giữ thương hiệu. Riêng quy cách, chất liệu, tỉ trọng dây trói/kg sản phẩm cho cua loại 1 và loại 2 cũng được quy định và giám sát chặt chẽ nên nhiều khách hàng rất an tâm và tin tưởng tiêu thụ mặt hàng cua Năm Căn – Cà Mau.\nCua Năm Căn – Cà Mau là một trong những đặc sản của vùng Đất Mũi Cà Mau. Cua Năm Căn – Cà Mau có thể chế biến được nhiều món ăn ngon, bổ dưỡng và rất thích hợp để làm quà tặng cho bạn bè người thân.",
  },
  {
    id: 21,
    lable: "Khô cá rún",
    image: "/images/kho-ca-run.jpg",
    description: "Nhờ có ngư trường đánh bắt rộng lớn, nguồn lợi thuỷ sản dồi dào nên hầu như mùa nào ngư dân thị trấn Cái Đôi Vàm, huyện Phú Tân, tỉnh Cà Mau cũng trúng mùa cá rún. Ngoài việc dùng làm thực phẩm tươi sống để nấu lẩu, nấu canh chua, kho lạt, chiên, nướng, ngư dân nơi xóm biển này còn sử dụng cá rún để làm khô. Mặc dù hiện nay sản lượng không còn nhiều nhưng từ lâu khô cá rún đã trở thành một đặc sản nổi tiếng của ngư dân làng biển thị trấn Cái Đôi Vàm, huyện Phú Tân, tỉnh Cà Mau.",
  },
  {
    id: 22,
    lable: "Khô cá ngát",
    image: "/images/kho-ca-ngat.jpg",
    description: "Cá ngát thuộc lớp cá da trơn, sống trong môi trường nước mặn, sinh sống nhiều ở sông rạch, cửa biển, ao đầm nuôi tôm. Ở vùng đất bãi bồi, đất rừng, đất ngập mặn ven biển và trong các ao đầm nuôi tôm ở Cà Mau rất thích hợp cho cá ngát sinh sống và phát triển. Ngoài việc chế biến các món ăn như nấu canh chua, nấu lẩu, nướng, kho lạt, cá ngát còn được làm khô. Và khô cá ngát cũng chính là đặc sản của vùng Đất Mũi Cà Mau.",
  },
  {
    id: 23,
    lable: "Vọp",
    image: "/images/vop.jpg",
    description: "Nói đến vọp thì trên dải đất Việt Nam này không có nơi đâu có thể thể sánh bằng Cà Mau. Vọp Cà Mau có trữ lượng lớn và từ lâu trở thành một loại đặc sản nổi tiếng khắp trong và ngoài nước.",
  },
  {
    id: 24,
    lable: "Cá cơm",
    image: "/images/ca-com.jpg",
    description: "Nhờ có ngư trường đánh bắt rộng lớn nên sản lượng khai thác, đánh bắt cá cơm hàng năm của ngư dân trong tỉnh Cà Mau là rất lớn. Từ lâu, cá cơm cùng với nhiều loại tôm, cá, mực khác đã trở thành một loại đặc sản của vùng biển Cà Mau.",
  },
  {
    id: 25,
    lable: "Cua cốm Cà Mau",
    image: "/images/cua-com.jpg",
    description: "Cua cốm hay còn gọi là cua 2 da. Cua cốm thực ra là cua biển sắp đến ngày lột xác (lột vỏ) để lớn lên và chuẩn bị thành cua lột. So với các loại cua biển khác như yếm vuông, y nhất, y nhì, y ba, gạch son thì cua cốm là loại cua rất hiếm và ngon nhất trong tất cả các loại cua.",
  },
  {
    id: 26,
    lable: "Khô mực Sông Đốc",
    image: "/images/kho-muc-song-doc.jpg",
    description: "Với lợi thế của nghề khai thác biển truyền thống của mình, từ lâu thị trấn Sông Đốc, huyện Trần Văn Thời, tỉnh Cà Mau trở thành một cửa biển sầm uất và sôi động nhất của khu vực Đồng bằng sông Cửu Long. Hàng năm, từ nghề khai thác, đánh bắt trên biển, Sông Đốc đã cung ứng hơn 100.000 tấn thủy sản các loại. Ngoài các loại thủy sản tươi sống, ngư dân làng biển Sông Đốc đã hình thành nên làng nghề chế biến cá khô truyền thống. Trong đó, sản phẩm chủ lực và nổi tiếng nhất là đặc sản khô mực Sông Đốc.",
  },
  {
    id: 27,
    lable: "Cá lẹp vàng",
    image: "/images/ca-lep-vang.jpg",
    description: "Với 3 mặt giáp biển, tỉnh Cà Mau có ngư trường đánh bắt rộng lớn và có trữ lượng hải sản lớn, phong phú về chủng loại. Ngoài các loại tôm cá có giá trị và sản lượng lớn như tôm, mực, ghẹ, cá hồng, cá sạo, cá thu, cá chim, cá mú, cá bớp… vùng biển Cà Mau còn một trữ lượng lớn cá lẹp vàng. Đây cũng là một trong những đặc sản của vùng Đất Mũi Cà Mau.",
  },
]