import React from "react";
import { getProductDetail } from "@/actions/products";
import { IProductDetail } from "@/lib/interface/interface";
import Head from "next/head";
import { Metadata } from "next";

type Props = {
  params: { id: string };
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const data: IProductDetail | null = await getProductDetail(params.id);

  return {
    title: `SeaMarketHub | ${data?.productName}`,
    description: `Chi tiết sản phẩm ${data?.productName}`,
  };
}

const ProductDetailPage: React.FC<Props> = async ({ params }) => {
  const data: IProductDetail | null = await getProductDetail(params.id);
  console.log(data);
  return (
    <div>
      <Head>
        <title>{`SeaMarketHub :: ${data?.productName}`}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {params.id}
    </div>
  );
};
export default ProductDetailPage;
