import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'

import { ThemeProvider } from '@/components/providers/theme-provider'
import '@/app/globals.css'
import Navbar from '@/components/navbar'
import Providers from '@/components/providers/session-provider'

const noto = Noto_Sans({ subsets: ['vietnamese'], weight: ["300", "400", "500", "600", "700"], style: ["normal", "italic"] })

export const metadata: Metadata = {
  title: 'SeaMarketHub | Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="vi" suppressHydrationWarning>
      <Providers>
        <body className={noto.className}>
          <ThemeProvider
            attribute='class'
            defaultTheme='dark'
            storageKey='seamarkethub-theme'
            enableSystem={false}
          >
            <Navbar />
            {children}
          </ThemeProvider>
        </body>
      </Providers>
    </html>
  )
}
