import '@/app/globals.css'
import { ModeToggle } from '@/components/ModeToggle'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { Noto_Sans } from 'next/font/google'

const noto = Noto_Sans({ subsets: ['vietnamese'], weight: ["300", "400", "500", "600", "700"], style: ["normal", "italic"] })

export const metadata = {
  title: 'SeaMarKetHub :: Login',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="vi">
      <body className={`${noto.className} flex items-center justify-center`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='dark'
          storageKey='seamarkethub-theme'
          enableSystem={false}
        >
          {children}
          <div className='absolute bottom-2 right-2'>
            <ModeToggle />
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
