import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import { Toaster } from "react-hot-toast";

import { NextProviders } from "@/components/providers/NextUIProvider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import "@/app/globals.css";
import Providers from "@/components/providers/session-provider";
import NavbarComponent from "@/components/layout/NavbarComponent";
import { ReduxProvider } from "@/redux/provider";
import SearchComponent from "@/components/layout/SearchComponent";

const noto = Noto_Sans({
  subsets: ["vietnamese"],
  weight: ["300", "400", "500", "600", "700", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "SeaMarketHub | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi" suppressHydrationWarning>
      <Providers>
        <body className={noto.className}>
          <NextProviders>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              storageKey="seamarkethub-theme"
              enableSystem={false}
            >
              <ReduxProvider>
                <NavbarComponent />
                <main className="max-w-[90rem] mx-auto px-4 sm:px-6 md:px-8 pb-5">
                  {children}
                </main>
                <Toaster
                  position="bottom-right"
                  reverseOrder={false}
                />
              </ReduxProvider>
            </ThemeProvider>
          </NextProviders>
        </body>
      </Providers>
    </html>
  );
}
